#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
sudo apt-get update
sudo apt-get -y install haproxy
echo "frontend  Abdelrahman-frontend
        bind *:80
        mode http
        default_backend Abdelrahman-backend

backend Abdelrahman-backend
        balance roundrobin
        server web-01 54.175.144.189:80 check
        server web-02 54.237.208.76:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
